server:
  port: 8080
  
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?autoReconnection=true
    username: root
    password: asd123
    driver-class-name: com.mysql.cj.jdbc.Driver
  ai:
    google:
      genai:
        api-key:
mybatis:
  type-aliases-package: com.sist.web.vo
  mapper-locations: mybatis/mapper/*.xml